import * as _0 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _1 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _2 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _3 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _4 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _5 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _6 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _7 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _8 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _9 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _10 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _11 from './ts-out/go-ibc/ibc/core/connection/v1/tx';
import * as _12 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _13 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _14 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _15 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _16 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _17 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _18 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _19 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _20 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _21 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _22 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _23 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _24 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _25 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _26 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _27 from './ts-out/go-ibc/ibc/core/client/v1/tx';
import * as _28 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _29 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _30 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _31 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _32 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _33 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _34 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _35 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _36 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _37 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _38 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _39 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _40 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _41 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _42 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _43 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _44 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _45 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _46 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _47 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _48 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _49 from './ts-out/go-ibc/ibc/core/channel/v1/tx';
import * as _50 from './ts-out/go-ibc/ibc/applications/transfer/v1/tx';
import * as _51 from './ts-out/go-ibc/ibc/applications/transfer/v1/tx';
import * as _52 from './ts-out/go-ibc/ibc/applications/transfer/v1/tx';
import * as _53 from './ts-out/go-ibc/ibc/applications/transfer/v1/tx';
import * as _54 from './ts-out/go-ibc/ibc/applications/transfer/v1/tx';
import * as _55 from './ts-out/go-ibc/ibc/applications/transfer/v1/tx';
import * as _56 from './ts-out/go-ibc/ibc/applications/interchain_accounts/host/v1/tx';
import * as _57 from './ts-out/go-ibc/ibc/applications/interchain_accounts/host/v1/tx';
import * as _58 from './ts-out/go-ibc/ibc/applications/interchain_accounts/host/v1/tx';
import * as _59 from './ts-out/go-ibc/ibc/applications/interchain_accounts/host/v1/tx';
import * as _60 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _61 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _62 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _63 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _64 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _65 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _66 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _67 from './ts-out/go-ibc/ibc/applications/interchain_accounts/controller/v1/tx';
import * as _68 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _69 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _70 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _71 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _72 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _73 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _74 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _75 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _76 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _77 from './ts-out/go-ibc/ibc/applications/fee/v1/tx';
import * as _78 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _79 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _80 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _81 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _82 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _83 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _84 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _85 from './ts-out/celestiaorg_cosmos-sdk/cosmos/vesting/v1beta1/tx';
import * as _86 from './ts-out/celestiaorg_cosmos-sdk/cosmos/upgrade/v1beta1/tx';
import * as _87 from './ts-out/celestiaorg_cosmos-sdk/cosmos/upgrade/v1beta1/tx';
import * as _88 from './ts-out/celestiaorg_cosmos-sdk/cosmos/upgrade/v1beta1/tx';
import * as _89 from './ts-out/celestiaorg_cosmos-sdk/cosmos/upgrade/v1beta1/tx';
import * as _90 from './ts-out/celestiaorg_cosmos-sdk/cosmos/upgrade/v1beta1/tx';
import * as _91 from './ts-out/celestiaorg_cosmos-sdk/cosmos/upgrade/v1beta1/tx';
import * as _92 from './ts-out/celestiaorg_cosmos-sdk/cosmos/base/abci/v1beta1/abci';
import * as _93 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _94 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _95 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _96 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _97 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _98 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _99 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _100 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _101 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _102 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _103 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _104 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _105 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _106 from './ts-out/celestiaorg_cosmos-sdk/cosmos/staking/v1beta1/tx';
import * as _107 from './ts-out/celestiaorg_cosmos-sdk/cosmos/slashing/v1beta1/tx';
import * as _108 from './ts-out/celestiaorg_cosmos-sdk/cosmos/slashing/v1beta1/tx';
import * as _109 from './ts-out/celestiaorg_cosmos-sdk/cosmos/slashing/v1beta1/tx';
import * as _110 from './ts-out/celestiaorg_cosmos-sdk/cosmos/slashing/v1beta1/tx';
import * as _111 from './ts-out/celestiaorg_cosmos-sdk/cosmos/nft/v1beta1/tx';
import * as _112 from './ts-out/celestiaorg_cosmos-sdk/cosmos/nft/v1beta1/tx';
import * as _113 from './ts-out/celestiaorg_cosmos-sdk/cosmos/nft/v1beta1/tx';
import * as _114 from './ts-out/celestiaorg_cosmos-sdk/cosmos/nft/v1beta1/tx';
import * as _115 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _116 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _117 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _118 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _119 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _120 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _121 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _122 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _123 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _124 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _125 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _126 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _127 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _128 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _129 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _130 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _131 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _132 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _133 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _134 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _135 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _136 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _137 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _138 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _139 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _140 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _141 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _142 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _143 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _144 from './ts-out/celestiaorg_cosmos-sdk/cosmos/group/v1/tx';
import * as _145 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _146 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _147 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _148 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _149 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _150 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _151 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _152 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _153 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _154 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1beta1/tx';
import * as _155 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _156 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _157 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _158 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _159 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _160 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _161 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _162 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _163 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _164 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _165 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _166 from './ts-out/celestiaorg_cosmos-sdk/cosmos/gov/v1/tx';
import * as _167 from './ts-out/celestiaorg_cosmos-sdk/cosmos/feegrant/v1beta1/tx';
import * as _168 from './ts-out/celestiaorg_cosmos-sdk/cosmos/feegrant/v1beta1/tx';
import * as _169 from './ts-out/celestiaorg_cosmos-sdk/cosmos/feegrant/v1beta1/tx';
import * as _170 from './ts-out/celestiaorg_cosmos-sdk/cosmos/feegrant/v1beta1/tx';
import * as _171 from './ts-out/celestiaorg_cosmos-sdk/cosmos/feegrant/v1beta1/tx';
import * as _172 from './ts-out/celestiaorg_cosmos-sdk/cosmos/feegrant/v1beta1/tx';
import * as _173 from './ts-out/celestiaorg_cosmos-sdk/cosmos/evidence/v1beta1/tx';
import * as _174 from './ts-out/celestiaorg_cosmos-sdk/cosmos/evidence/v1beta1/tx';
import * as _175 from './ts-out/celestiaorg_cosmos-sdk/cosmos/evidence/v1beta1/tx';
import * as _176 from './ts-out/celestiaorg_cosmos-sdk/cosmos/evidence/v1beta1/tx';
import * as _177 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _178 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _179 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _180 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _181 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _182 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _183 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _184 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _185 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _186 from './ts-out/celestiaorg_cosmos-sdk/cosmos/distribution/v1beta1/tx';
import * as _187 from './ts-out/celestiaorg_cosmos-sdk/cosmos/crisis/v1beta1/tx';
import * as _188 from './ts-out/celestiaorg_cosmos-sdk/cosmos/crisis/v1beta1/tx';
import * as _189 from './ts-out/celestiaorg_cosmos-sdk/cosmos/crisis/v1beta1/tx';
import * as _190 from './ts-out/celestiaorg_cosmos-sdk/cosmos/crisis/v1beta1/tx';
import * as _191 from './ts-out/celestiaorg_cosmos-sdk/cosmos/base/reflection/v2alpha1/reflection';
import * as _192 from './ts-out/celestiaorg_cosmos-sdk/cosmos/bank/v1beta1/tx';
import * as _193 from './ts-out/celestiaorg_cosmos-sdk/cosmos/bank/v1beta1/tx';
import * as _194 from './ts-out/celestiaorg_cosmos-sdk/cosmos/bank/v1beta1/tx';
import * as _195 from './ts-out/celestiaorg_cosmos-sdk/cosmos/bank/v1beta1/tx';
import * as _196 from './ts-out/celestiaorg_cosmos-sdk/cosmos/bank/v1beta1/tx';
import * as _197 from './ts-out/celestiaorg_cosmos-sdk/cosmos/bank/v1beta1/tx';
import * as _198 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _199 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _200 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _201 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _202 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _203 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _204 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _205 from './ts-out/celestiaorg_cosmos-sdk/cosmos/authz/v1beta1/tx';
import * as _206 from './ts-out/celestia-app/celestia/upgrade/v1/types';
import * as _207 from './ts-out/celestia-app/celestia/qgb/v1/tx';
import * as _208 from './ts-out/celestia-app/celestia/qgb/v1/tx';
import * as _209 from './ts-out/celestia-app/celestia/qgb/v1/tx';
import * as _210 from './ts-out/celestia-app/celestia/qgb/v1/tx';
import * as _211 from './ts-out/celestia-app/celestia/blob/v1/tx';
import * as _212 from './ts-out/celestia-app/celestia/blob/v1/tx';
import * as _213 from './ts-out/celestia-app/celestia/blob/v1/tx';
import * as _214 from './ts-out/celestia-app/celestia/blob/v1/tx';

export const Msgs = [
  { parser: _0.MsgConnectionOpenInit, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenInit' },
  { parser: _1.MsgConnectionOpenInitResponse, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenInitResponse' },
  { parser: _2.MsgConnectionOpenTry, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenTry' },
  { parser: _3.MsgConnectionOpenTryResponse, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenTryResponse' },
  { parser: _4.MsgConnectionOpenAck, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenAck' },
  { parser: _5.MsgConnectionOpenAckResponse, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenAckResponse' },
  { parser: _6.MsgConnectionOpenConfirm, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenConfirm' },
  { parser: _7.MsgConnectionOpenConfirmResponse, typeUrl: '/ibc.core.connection.v1.MsgConnectionOpenConfirmResponse' },
  { parser: _8.MsgUpdateParams, typeUrl: '/ibc.core.connection.v1.MsgUpdateParams' },
  { parser: _9.MsgUpdateParamsResponse, typeUrl: '/ibc.core.connection.v1.MsgUpdateParamsResponse' },
  { parser: _10.MsgServiceName, typeUrl: '/ibc.core.connection.v1.MsgServiceName' },
  { parser: _11.MsgClientImpl, typeUrl: '/ibc.core.connection.v1.MsgClientImpl' },
  { parser: _12.MsgCreateClient, typeUrl: '/ibc.core.client.v1.MsgCreateClient' },
  { parser: _13.MsgCreateClientResponse, typeUrl: '/ibc.core.client.v1.MsgCreateClientResponse' },
  { parser: _14.MsgUpdateClient, typeUrl: '/ibc.core.client.v1.MsgUpdateClient' },
  { parser: _15.MsgUpdateClientResponse, typeUrl: '/ibc.core.client.v1.MsgUpdateClientResponse' },
  { parser: _16.MsgUpgradeClient, typeUrl: '/ibc.core.client.v1.MsgUpgradeClient' },
  { parser: _17.MsgUpgradeClientResponse, typeUrl: '/ibc.core.client.v1.MsgUpgradeClientResponse' },
  { parser: _18.MsgSubmitMisbehaviour, typeUrl: '/ibc.core.client.v1.MsgSubmitMisbehaviour' },
  { parser: _19.MsgSubmitMisbehaviourResponse, typeUrl: '/ibc.core.client.v1.MsgSubmitMisbehaviourResponse' },
  { parser: _20.MsgRecoverClient, typeUrl: '/ibc.core.client.v1.MsgRecoverClient' },
  { parser: _21.MsgRecoverClientResponse, typeUrl: '/ibc.core.client.v1.MsgRecoverClientResponse' },
  { parser: _22.MsgIBCSoftwareUpgrade, typeUrl: '/ibc.core.client.v1.MsgIBCSoftwareUpgrade' },
  { parser: _23.MsgIBCSoftwareUpgradeResponse, typeUrl: '/ibc.core.client.v1.MsgIBCSoftwareUpgradeResponse' },
  { parser: _24.MsgUpdateParams, typeUrl: '/ibc.core.client.v1.MsgUpdateParams' },
  { parser: _25.MsgUpdateParamsResponse, typeUrl: '/ibc.core.client.v1.MsgUpdateParamsResponse' },
  { parser: _26.MsgServiceName, typeUrl: '/ibc.core.client.v1.MsgServiceName' },
  { parser: _27.MsgClientImpl, typeUrl: '/ibc.core.client.v1.MsgClientImpl' },
  { parser: _28.MsgChannelOpenInit, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenInit' },
  { parser: _29.MsgChannelOpenInitResponse, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenInitResponse' },
  { parser: _30.MsgChannelOpenTry, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenTry' },
  { parser: _31.MsgChannelOpenTryResponse, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenTryResponse' },
  { parser: _32.MsgChannelOpenAck, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenAck' },
  { parser: _33.MsgChannelOpenAckResponse, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenAckResponse' },
  { parser: _34.MsgChannelOpenConfirm, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenConfirm' },
  { parser: _35.MsgChannelOpenConfirmResponse, typeUrl: '/ibc.core.channel.v1.MsgChannelOpenConfirmResponse' },
  { parser: _36.MsgChannelCloseInit, typeUrl: '/ibc.core.channel.v1.MsgChannelCloseInit' },
  { parser: _37.MsgChannelCloseInitResponse, typeUrl: '/ibc.core.channel.v1.MsgChannelCloseInitResponse' },
  { parser: _38.MsgChannelCloseConfirm, typeUrl: '/ibc.core.channel.v1.MsgChannelCloseConfirm' },
  { parser: _39.MsgChannelCloseConfirmResponse, typeUrl: '/ibc.core.channel.v1.MsgChannelCloseConfirmResponse' },
  { parser: _40.MsgRecvPacket, typeUrl: '/ibc.core.channel.v1.MsgRecvPacket' },
  { parser: _41.MsgRecvPacketResponse, typeUrl: '/ibc.core.channel.v1.MsgRecvPacketResponse' },
  { parser: _42.MsgTimeout, typeUrl: '/ibc.core.channel.v1.MsgTimeout' },
  { parser: _43.MsgTimeoutResponse, typeUrl: '/ibc.core.channel.v1.MsgTimeoutResponse' },
  { parser: _44.MsgTimeoutOnClose, typeUrl: '/ibc.core.channel.v1.MsgTimeoutOnClose' },
  { parser: _45.MsgTimeoutOnCloseResponse, typeUrl: '/ibc.core.channel.v1.MsgTimeoutOnCloseResponse' },
  { parser: _46.MsgAcknowledgement, typeUrl: '/ibc.core.channel.v1.MsgAcknowledgement' },
  { parser: _47.MsgAcknowledgementResponse, typeUrl: '/ibc.core.channel.v1.MsgAcknowledgementResponse' },
  { parser: _48.MsgServiceName, typeUrl: '/ibc.core.channel.v1.MsgServiceName' },
  { parser: _49.MsgClientImpl, typeUrl: '/ibc.core.channel.v1.MsgClientImpl' },
  { parser: _50.MsgTransfer, typeUrl: '/ibc.applications.transfer.v1.MsgTransfer' },
  { parser: _51.MsgTransferResponse, typeUrl: '/ibc.applications.transfer.v1.MsgTransferResponse' },
  { parser: _52.MsgUpdateParams, typeUrl: '/ibc.applications.transfer.v1.MsgUpdateParams' },
  { parser: _53.MsgUpdateParamsResponse, typeUrl: '/ibc.applications.transfer.v1.MsgUpdateParamsResponse' },
  { parser: _54.MsgServiceName, typeUrl: '/ibc.applications.transfer.v1.MsgServiceName' },
  { parser: _55.MsgClientImpl, typeUrl: '/ibc.applications.transfer.v1.MsgClientImpl' },
  { parser: _56.MsgUpdateParams, typeUrl: '/ibc.applications.interchain_accounts.host.v1.MsgUpdateParams' },
  { parser: _57.MsgUpdateParamsResponse, typeUrl: '/ibc.applications.interchain_accounts.host.v1.MsgUpdateParamsResponse' },
  { parser: _58.MsgServiceName, typeUrl: '/ibc.applications.interchain_accounts.host.v1.MsgServiceName' },
  { parser: _59.MsgClientImpl, typeUrl: '/ibc.applications.interchain_accounts.host.v1.MsgClientImpl' },
  { parser: _60.MsgRegisterInterchainAccount, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccount' },
  { parser: _61.MsgRegisterInterchainAccountResponse, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccountResponse' },
  { parser: _62.MsgSendTx, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgSendTx' },
  { parser: _63.MsgSendTxResponse, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgSendTxResponse' },
  { parser: _64.MsgUpdateParams, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgUpdateParams' },
  { parser: _65.MsgUpdateParamsResponse, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgUpdateParamsResponse' },
  { parser: _66.MsgServiceName, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgServiceName' },
  { parser: _67.MsgClientImpl, typeUrl: '/ibc.applications.interchain_accounts.controller.v1.MsgClientImpl' },
  { parser: _68.MsgRegisterPayee, typeUrl: '/ibc.applications.fee.v1.MsgRegisterPayee' },
  { parser: _69.MsgRegisterPayeeResponse, typeUrl: '/ibc.applications.fee.v1.MsgRegisterPayeeResponse' },
  { parser: _70.MsgRegisterCounterpartyPayee, typeUrl: '/ibc.applications.fee.v1.MsgRegisterCounterpartyPayee' },
  { parser: _71.MsgRegisterCounterpartyPayeeResponse, typeUrl: '/ibc.applications.fee.v1.MsgRegisterCounterpartyPayeeResponse' },
  { parser: _72.MsgPayPacketFee, typeUrl: '/ibc.applications.fee.v1.MsgPayPacketFee' },
  { parser: _73.MsgPayPacketFeeResponse, typeUrl: '/ibc.applications.fee.v1.MsgPayPacketFeeResponse' },
  { parser: _74.MsgPayPacketFeeAsync, typeUrl: '/ibc.applications.fee.v1.MsgPayPacketFeeAsync' },
  { parser: _75.MsgPayPacketFeeAsyncResponse, typeUrl: '/ibc.applications.fee.v1.MsgPayPacketFeeAsyncResponse' },
  { parser: _76.MsgServiceName, typeUrl: '/ibc.applications.fee.v1.MsgServiceName' },
  { parser: _77.MsgClientImpl, typeUrl: '/ibc.applications.fee.v1.MsgClientImpl' },
  { parser: _78.MsgCreateVestingAccount, typeUrl: '/cosmos.vesting.v1beta1.MsgCreateVestingAccount' },
  { parser: _79.MsgCreateVestingAccountResponse, typeUrl: '/cosmos.vesting.v1beta1.MsgCreateVestingAccountResponse' },
  { parser: _80.MsgCreatePermanentLockedAccount, typeUrl: '/cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccount' },
  { parser: _81.MsgCreatePermanentLockedAccountResponse, typeUrl: '/cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccountResponse' },
  { parser: _82.MsgCreatePeriodicVestingAccount, typeUrl: '/cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount' },
  { parser: _83.MsgCreatePeriodicVestingAccountResponse, typeUrl: '/cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccountResponse' },
  { parser: _84.MsgServiceName, typeUrl: '/cosmos.vesting.v1beta1.MsgServiceName' },
  { parser: _85.MsgClientImpl, typeUrl: '/cosmos.vesting.v1beta1.MsgClientImpl' },
  { parser: _86.MsgSoftwareUpgrade, typeUrl: '/cosmos.upgrade.v1beta1.MsgSoftwareUpgrade' },
  { parser: _87.MsgSoftwareUpgradeResponse, typeUrl: '/cosmos.upgrade.v1beta1.MsgSoftwareUpgradeResponse' },
  { parser: _88.MsgCancelUpgrade, typeUrl: '/cosmos.upgrade.v1beta1.MsgCancelUpgrade' },
  { parser: _89.MsgCancelUpgradeResponse, typeUrl: '/cosmos.upgrade.v1beta1.MsgCancelUpgradeResponse' },
  { parser: _90.MsgServiceName, typeUrl: '/cosmos.upgrade.v1beta1.MsgServiceName' },
  { parser: _91.MsgClientImpl, typeUrl: '/cosmos.upgrade.v1beta1.MsgClientImpl' },
  { parser: _92.MsgData, typeUrl: '/cosmos.base.abci.v1beta1.MsgData' },
  { parser: _93.MsgCreateValidator, typeUrl: '/cosmos.staking.v1beta1.MsgCreateValidator' },
  { parser: _94.MsgCreateValidatorResponse, typeUrl: '/cosmos.staking.v1beta1.MsgCreateValidatorResponse' },
  { parser: _95.MsgEditValidator, typeUrl: '/cosmos.staking.v1beta1.MsgEditValidator' },
  { parser: _96.MsgEditValidatorResponse, typeUrl: '/cosmos.staking.v1beta1.MsgEditValidatorResponse' },
  { parser: _97.MsgDelegate, typeUrl: '/cosmos.staking.v1beta1.MsgDelegate' },
  { parser: _98.MsgDelegateResponse, typeUrl: '/cosmos.staking.v1beta1.MsgDelegateResponse' },
  { parser: _99.MsgBeginRedelegate, typeUrl: '/cosmos.staking.v1beta1.MsgBeginRedelegate' },
  { parser: _100.MsgBeginRedelegateResponse, typeUrl: '/cosmos.staking.v1beta1.MsgBeginRedelegateResponse' },
  { parser: _101.MsgUndelegate, typeUrl: '/cosmos.staking.v1beta1.MsgUndelegate' },
  { parser: _102.MsgUndelegateResponse, typeUrl: '/cosmos.staking.v1beta1.MsgUndelegateResponse' },
  { parser: _103.MsgCancelUnbondingDelegation, typeUrl: '/cosmos.staking.v1beta1.MsgCancelUnbondingDelegation' },
  { parser: _104.MsgCancelUnbondingDelegationResponse, typeUrl: '/cosmos.staking.v1beta1.MsgCancelUnbondingDelegationResponse' },
  { parser: _105.MsgServiceName, typeUrl: '/cosmos.staking.v1beta1.MsgServiceName' },
  { parser: _106.MsgClientImpl, typeUrl: '/cosmos.staking.v1beta1.MsgClientImpl' },
  { parser: _107.MsgUnjail, typeUrl: '/cosmos.slashing.v1beta1.MsgUnjail' },
  { parser: _108.MsgUnjailResponse, typeUrl: '/cosmos.slashing.v1beta1.MsgUnjailResponse' },
  { parser: _109.MsgServiceName, typeUrl: '/cosmos.slashing.v1beta1.MsgServiceName' },
  { parser: _110.MsgClientImpl, typeUrl: '/cosmos.slashing.v1beta1.MsgClientImpl' },
  { parser: _111.MsgSend, typeUrl: '/cosmos.nft.v1beta1.MsgSend' },
  { parser: _112.MsgSendResponse, typeUrl: '/cosmos.nft.v1beta1.MsgSendResponse' },
  { parser: _113.MsgServiceName, typeUrl: '/cosmos.nft.v1beta1.MsgServiceName' },
  { parser: _114.MsgClientImpl, typeUrl: '/cosmos.nft.v1beta1.MsgClientImpl' },
  { parser: _115.MsgCreateGroup, typeUrl: '/cosmos.group.v1.MsgCreateGroup' },
  { parser: _116.MsgCreateGroupResponse, typeUrl: '/cosmos.group.v1.MsgCreateGroupResponse' },
  { parser: _117.MsgUpdateGroupMembers, typeUrl: '/cosmos.group.v1.MsgUpdateGroupMembers' },
  { parser: _118.MsgUpdateGroupMembersResponse, typeUrl: '/cosmos.group.v1.MsgUpdateGroupMembersResponse' },
  { parser: _119.MsgUpdateGroupAdmin, typeUrl: '/cosmos.group.v1.MsgUpdateGroupAdmin' },
  { parser: _120.MsgUpdateGroupAdminResponse, typeUrl: '/cosmos.group.v1.MsgUpdateGroupAdminResponse' },
  { parser: _121.MsgUpdateGroupMetadata, typeUrl: '/cosmos.group.v1.MsgUpdateGroupMetadata' },
  { parser: _122.MsgUpdateGroupMetadataResponse, typeUrl: '/cosmos.group.v1.MsgUpdateGroupMetadataResponse' },
  { parser: _123.MsgCreateGroupPolicy, typeUrl: '/cosmos.group.v1.MsgCreateGroupPolicy' },
  { parser: _124.MsgCreateGroupPolicyResponse, typeUrl: '/cosmos.group.v1.MsgCreateGroupPolicyResponse' },
  { parser: _125.MsgUpdateGroupPolicyAdmin, typeUrl: '/cosmos.group.v1.MsgUpdateGroupPolicyAdmin' },
  { parser: _126.MsgCreateGroupWithPolicy, typeUrl: '/cosmos.group.v1.MsgCreateGroupWithPolicy' },
  { parser: _127.MsgCreateGroupWithPolicyResponse, typeUrl: '/cosmos.group.v1.MsgCreateGroupWithPolicyResponse' },
  { parser: _128.MsgUpdateGroupPolicyAdminResponse, typeUrl: '/cosmos.group.v1.MsgUpdateGroupPolicyAdminResponse' },
  { parser: _129.MsgUpdateGroupPolicyDecisionPolicy, typeUrl: '/cosmos.group.v1.MsgUpdateGroupPolicyDecisionPolicy' },
  { parser: _130.MsgUpdateGroupPolicyDecisionPolicyResponse, typeUrl: '/cosmos.group.v1.MsgUpdateGroupPolicyDecisionPolicyResponse' },
  { parser: _131.MsgUpdateGroupPolicyMetadata, typeUrl: '/cosmos.group.v1.MsgUpdateGroupPolicyMetadata' },
  { parser: _132.MsgUpdateGroupPolicyMetadataResponse, typeUrl: '/cosmos.group.v1.MsgUpdateGroupPolicyMetadataResponse' },
  { parser: _133.MsgSubmitProposal, typeUrl: '/cosmos.group.v1.MsgSubmitProposal' },
  { parser: _134.MsgSubmitProposalResponse, typeUrl: '/cosmos.group.v1.MsgSubmitProposalResponse' },
  { parser: _135.MsgWithdrawProposal, typeUrl: '/cosmos.group.v1.MsgWithdrawProposal' },
  { parser: _136.MsgWithdrawProposalResponse, typeUrl: '/cosmos.group.v1.MsgWithdrawProposalResponse' },
  { parser: _137.MsgVote, typeUrl: '/cosmos.group.v1.MsgVote' },
  { parser: _138.MsgVoteResponse, typeUrl: '/cosmos.group.v1.MsgVoteResponse' },
  { parser: _139.MsgExec, typeUrl: '/cosmos.group.v1.MsgExec' },
  { parser: _140.MsgExecResponse, typeUrl: '/cosmos.group.v1.MsgExecResponse' },
  { parser: _141.MsgLeaveGroup, typeUrl: '/cosmos.group.v1.MsgLeaveGroup' },
  { parser: _142.MsgLeaveGroupResponse, typeUrl: '/cosmos.group.v1.MsgLeaveGroupResponse' },
  { parser: _143.MsgServiceName, typeUrl: '/cosmos.group.v1.MsgServiceName' },
  { parser: _144.MsgClientImpl, typeUrl: '/cosmos.group.v1.MsgClientImpl' },
  { parser: _145.MsgSubmitProposal, typeUrl: '/cosmos.gov.v1beta1.MsgSubmitProposal' },
  { parser: _146.MsgSubmitProposalResponse, typeUrl: '/cosmos.gov.v1beta1.MsgSubmitProposalResponse' },
  { parser: _147.MsgVote, typeUrl: '/cosmos.gov.v1beta1.MsgVote' },
  { parser: _148.MsgVoteResponse, typeUrl: '/cosmos.gov.v1beta1.MsgVoteResponse' },
  { parser: _149.MsgVoteWeighted, typeUrl: '/cosmos.gov.v1beta1.MsgVoteWeighted' },
  { parser: _150.MsgVoteWeightedResponse, typeUrl: '/cosmos.gov.v1beta1.MsgVoteWeightedResponse' },
  { parser: _151.MsgDeposit, typeUrl: '/cosmos.gov.v1beta1.MsgDeposit' },
  { parser: _152.MsgDepositResponse, typeUrl: '/cosmos.gov.v1beta1.MsgDepositResponse' },
  { parser: _153.MsgServiceName, typeUrl: '/cosmos.gov.v1beta1.MsgServiceName' },
  { parser: _154.MsgClientImpl, typeUrl: '/cosmos.gov.v1beta1.MsgClientImpl' },
  { parser: _155.MsgSubmitProposal, typeUrl: '/cosmos.gov.v1.MsgSubmitProposal' },
  { parser: _156.MsgSubmitProposalResponse, typeUrl: '/cosmos.gov.v1.MsgSubmitProposalResponse' },
  { parser: _157.MsgExecLegacyContent, typeUrl: '/cosmos.gov.v1.MsgExecLegacyContent' },
  { parser: _158.MsgExecLegacyContentResponse, typeUrl: '/cosmos.gov.v1.MsgExecLegacyContentResponse' },
  { parser: _159.MsgVote, typeUrl: '/cosmos.gov.v1.MsgVote' },
  { parser: _160.MsgVoteResponse, typeUrl: '/cosmos.gov.v1.MsgVoteResponse' },
  { parser: _161.MsgVoteWeighted, typeUrl: '/cosmos.gov.v1.MsgVoteWeighted' },
  { parser: _162.MsgVoteWeightedResponse, typeUrl: '/cosmos.gov.v1.MsgVoteWeightedResponse' },
  { parser: _163.MsgDeposit, typeUrl: '/cosmos.gov.v1.MsgDeposit' },
  { parser: _164.MsgDepositResponse, typeUrl: '/cosmos.gov.v1.MsgDepositResponse' },
  { parser: _165.MsgServiceName, typeUrl: '/cosmos.gov.v1.MsgServiceName' },
  { parser: _166.MsgClientImpl, typeUrl: '/cosmos.gov.v1.MsgClientImpl' },
  { parser: _167.MsgGrantAllowance, typeUrl: '/cosmos.feegrant.v1beta1.MsgGrantAllowance' },
  { parser: _168.MsgGrantAllowanceResponse, typeUrl: '/cosmos.feegrant.v1beta1.MsgGrantAllowanceResponse' },
  { parser: _169.MsgRevokeAllowance, typeUrl: '/cosmos.feegrant.v1beta1.MsgRevokeAllowance' },
  { parser: _170.MsgRevokeAllowanceResponse, typeUrl: '/cosmos.feegrant.v1beta1.MsgRevokeAllowanceResponse' },
  { parser: _171.MsgServiceName, typeUrl: '/cosmos.feegrant.v1beta1.MsgServiceName' },
  { parser: _172.MsgClientImpl, typeUrl: '/cosmos.feegrant.v1beta1.MsgClientImpl' },
  { parser: _173.MsgSubmitEvidence, typeUrl: '/cosmos.evidence.v1beta1.MsgSubmitEvidence' },
  { parser: _174.MsgSubmitEvidenceResponse, typeUrl: '/cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse' },
  { parser: _175.MsgServiceName, typeUrl: '/cosmos.evidence.v1beta1.MsgServiceName' },
  { parser: _176.MsgClientImpl, typeUrl: '/cosmos.evidence.v1beta1.MsgClientImpl' },
  { parser: _177.MsgSetWithdrawAddress, typeUrl: '/cosmos.distribution.v1beta1.MsgSetWithdrawAddress' },
  { parser: _178.MsgSetWithdrawAddressResponse, typeUrl: '/cosmos.distribution.v1beta1.MsgSetWithdrawAddressResponse' },
  { parser: _179.MsgWithdrawDelegatorReward, typeUrl: '/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward' },
  { parser: _180.MsgWithdrawDelegatorRewardResponse, typeUrl: '/cosmos.distribution.v1beta1.MsgWithdrawDelegatorRewardResponse' },
  { parser: _181.MsgWithdrawValidatorCommission, typeUrl: '/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission' },
  { parser: _182.MsgWithdrawValidatorCommissionResponse, typeUrl: '/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommissionResponse' },
  { parser: _183.MsgFundCommunityPool, typeUrl: '/cosmos.distribution.v1beta1.MsgFundCommunityPool' },
  { parser: _184.MsgFundCommunityPoolResponse, typeUrl: '/cosmos.distribution.v1beta1.MsgFundCommunityPoolResponse' },
  { parser: _185.MsgServiceName, typeUrl: '/cosmos.distribution.v1beta1.MsgServiceName' },
  { parser: _186.MsgClientImpl, typeUrl: '/cosmos.distribution.v1beta1.MsgClientImpl' },
  { parser: _187.MsgVerifyInvariant, typeUrl: '/cosmos.crisis.v1beta1.MsgVerifyInvariant' },
  { parser: _188.MsgVerifyInvariantResponse, typeUrl: '/cosmos.crisis.v1beta1.MsgVerifyInvariantResponse' },
  { parser: _189.MsgServiceName, typeUrl: '/cosmos.crisis.v1beta1.MsgServiceName' },
  { parser: _190.MsgClientImpl, typeUrl: '/cosmos.crisis.v1beta1.MsgClientImpl' },
  { parser: _191.MsgDescriptor, typeUrl: '/cosmos.base.reflection.v2alpha1.MsgDescriptor' },
  { parser: _192.MsgSend, typeUrl: '/cosmos.bank.v1beta1.MsgSend' },
  { parser: _193.MsgSendResponse, typeUrl: '/cosmos.bank.v1beta1.MsgSendResponse' },
  { parser: _194.MsgMultiSend, typeUrl: '/cosmos.bank.v1beta1.MsgMultiSend' },
  { parser: _195.MsgMultiSendResponse, typeUrl: '/cosmos.bank.v1beta1.MsgMultiSendResponse' },
  { parser: _196.MsgServiceName, typeUrl: '/cosmos.bank.v1beta1.MsgServiceName' },
  { parser: _197.MsgClientImpl, typeUrl: '/cosmos.bank.v1beta1.MsgClientImpl' },
  { parser: _198.MsgGrant, typeUrl: '/cosmos.authz.v1beta1.MsgGrant' },
  { parser: _199.MsgExecResponse, typeUrl: '/cosmos.authz.v1beta1.MsgExecResponse' },
  { parser: _200.MsgExec, typeUrl: '/cosmos.authz.v1beta1.MsgExec' },
  { parser: _201.MsgGrantResponse, typeUrl: '/cosmos.authz.v1beta1.MsgGrantResponse' },
  { parser: _202.MsgRevoke, typeUrl: '/cosmos.authz.v1beta1.MsgRevoke' },
  { parser: _203.MsgRevokeResponse, typeUrl: '/cosmos.authz.v1beta1.MsgRevokeResponse' },
  { parser: _204.MsgServiceName, typeUrl: '/cosmos.authz.v1beta1.MsgServiceName' },
  { parser: _205.MsgClientImpl, typeUrl: '/cosmos.authz.v1beta1.MsgClientImpl' },
  { parser: _206.MsgVersionChange, typeUrl: '/celestia.upgrade.v1.MsgVersionChange' },
  { parser: _207.MsgRegisterEVMAddress, typeUrl: '/celestia.qgb.v1.MsgRegisterEVMAddress' },
  { parser: _208.MsgRegisterEVMAddressResponse, typeUrl: '/celestia.qgb.v1.MsgRegisterEVMAddressResponse' },
  { parser: _209.MsgServiceName, typeUrl: '/celestia.qgb.v1.MsgServiceName' },
  { parser: _210.MsgClientImpl, typeUrl: '/celestia.qgb.v1.MsgClientImpl' },
  { parser: _211.MsgPayForBlobs, typeUrl: '/celestia.blob.v1.MsgPayForBlobs' },
  { parser: _212.MsgPayForBlobsResponse, typeUrl: '/celestia.blob.v1.MsgPayForBlobsResponse' },
  { parser: _213.MsgServiceName, typeUrl: '/celestia.blob.v1.MsgServiceName' },
  { parser: _214.MsgClientImpl, typeUrl: '/celestia.blob.v1.MsgClientImpl' },
];